package blog.anirbanm.cd.model.am;

import blog.anirbanm.cd.model.am.common.CdModule;
import blog.anirbanm.cd.types.Employees;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 11:52:59 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CdModuleImpl extends ApplicationModuleImpl implements CdModule {
    /**
     * This is the default constructor (do not remove).
     */
    public CdModuleImpl() {
    }
    
    public Employees acceptAndModifyEmployee(Employees employee) {
        if (employee != null) {
            if (employee.getEmployeeId() > 200) {
                employee.setJobId("PRESIDENT");
            }
        }
        return employee;
    }
}

