package blog.anirbanm.cd.model.am.common;

import blog.anirbanm.cd.types.Employees;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 12:02:57 IST 2018
// ---------------------------------------------------------------------
public interface CdModule extends ApplicationModule {
    Employees acceptAndModifyEmployee(Employees employee);
}

